# Uncomment the next line to define a global platform for your project

 

target 'FirebaseDatabase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
platform :ios, '9.0'
  # Pods for FirebaseDatabase

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'FirebaseUI'
end
